[package]
description = "Substrate offchain workers"
name = "sc-offchain"
version = "2.0.0-rc4"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bytes = "0.5.5"
sc-client-api = { version = "2.0.0-rc4", path = "../api" }
sp-api = { version = "2.0.0-rc4", path = "../../primitives/api" }
fnv = "1.0.7"
futures = "0.3.5"
futures-timer = "3.0.2"
log = "0.4.8"
threadpool = "1.8.1"
num_cpus = "1.13.0"
sp-offchain = { version = "2.0.0-rc4", path = "../../primitives/offchain" }
codec = { package = "parity-scale-codec", version = "1.3.1", features = ["derive"] }
parking_lot = "0.10.2"
sp-core = { version = "2.0.0-rc4", path = "../../primitives/core" }
rand = "0.7.3"
sp-runtime = { version = "2.0.0-rc4", path = "../../primitives/runtime" }
sp-utils = { version = "2.0.0-rc4", path = "../../primitives/utils" }
sc-network = { version = "0.8.0-rc4", path = "../network" }
sc-keystore = { version = "2.0.0-rc4", path = "../keystore" }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
hyper = "0.13.6"
hyper-rustls = "0.21.0"

[dev-dependencies]
env_logger = "0.7.1"
sc-client-db = { version = "0.8.0-rc4", default-features = true, path = "../db/" }
sc-transaction-pool = { version = "2.0.0-rc4", path = "../../client/transaction-pool" }
sp-transaction-pool = { version = "2.0.0-rc4", path = "../../primitives/transaction-pool" }
substrate-test-runtime-client = { version = "2.0.0-rc4", path = "../../test-utils/runtime/client" }
tokio = "0.2.21"
lazy_static = "1.4.0"

[features]
default = []
