[package]
name = "node-browser-testing"
version = "2.0.0-rc4"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Tests for the in-browser light client."
edition = "2018"
license = "Apache-2.0"

[dependencies]
futures-timer = "3.0.2"
libp2p = { version = "0.21.1", default-features = false }
jsonrpc-core = "14.2.0"
serde = "1.0.114"
serde_json = "1.0.56"
wasm-bindgen = { version = "0.2.62", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.12"
wasm-bindgen-test = "0.3.12"
futures = "0.3.5"

node-cli = { path = "../cli", default-features = false, features = ["browser"] , version = "2.0.0-rc4"}
sc-rpc-api = { path = "../../../client/rpc-api" , version = "0.8.0-rc4"}
