[package]
name = "substrate-browser-utils"
version = "0.8.0-rc4"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Utilities for creating a browser light-client."
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = { version = "0.1.29", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.29" }
log = "0.4.8"
libp2p-wasm-ext = { version = "0.20.1", features = ["websocket"] }
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
js-sys = "0.3.39"
wasm-bindgen = "0.2.62"
wasm-bindgen-futures = "0.4.12"
kvdb-web = "0.7.0"
sp-database = { version = "2.0.0-rc4", path = "../../primitives/database" }
sc-informant = { version = "0.8.0-rc4", path = "../../client/informant" }
sc-service = { version = "0.8.0-rc4", path = "../../client/service", default-features = false }
sc-network = { path = "../../client/network", version = "0.8.0-rc4"}
sc-chain-spec = { path = "../../client/chain-spec", version = "2.0.0-rc4"}

# Imported just for the `no_cc` feature
clear_on_drop = { version = "0.2.4", features = ["no_cc"] }
# Imported just for the `wasm-bindgen` feature
rand6 = { package = "rand", version = "0.6.5", features = ["wasm-bindgen"] }
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
futures-timer = { version = "3.0.2", features = ["wasm-bindgen"] }
chrono = { version = "0.4.13", features = ["wasmbind"] }
