[package]
name = "sc-keystore"
version = "2.0.0-rc4"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Keystore (and session key management) for ed25519 based chains like Polkadot."
documentation = "https://docs.rs/sc-keystore"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
derive_more = "0.99.9"
sp-core = { version = "2.0.0-rc4", path = "../../primitives/core" }
sp-application-crypto = { version = "2.0.0-rc4", path = "../../primitives/application-crypto" }
hex = "0.4.2"
merlin = { version = "2.0.0", default-features = false }
parking_lot = "0.10.2"
rand = "0.7.3"
serde_json = "1.0.56"
subtle = "2.2.3"

[dev-dependencies]
tempfile = "3.1.0"
