[package]
name = "sc-telemetry"
version = "2.0.0-rc4"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Telemetry utils"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-telemetry"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
parking_lot = "0.10.2"
futures = "0.3.5"
futures-timer = "3.0.2"
wasm-timer = "0.2.4"
libp2p = { version = "0.21.1", default-features = false, features = ["dns", "tcp-async-std", "wasm-ext", "websocket"] }
log = "0.4.8"
pin-project = "0.4.22"
rand = "0.7.3"
serde = { version = "1.0.114", features = ["derive"] }
slog = { version = "2.5.2", features = ["nested-values"] }
slog-json = { version = "2.3.0", features = ["nested-values"] }
slog-scope = "4.3.0"
take_mut = "0.2.2"
void = "1.0.2"
