[package]
name = "pallet-staking-reward-curve"
version = "2.0.0-rc4"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Reward Curve for FRAME staking pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.33", features = ["full", "visit"] }
quote = "1.0.7"
proc-macro2 = "1.0.18"
proc-macro-crate = "0.1.5"

[dev-dependencies]
sp-runtime = { version = "2.0.0-rc4", path = "../../../primitives/runtime" }
